### ISSUE TITLE
Intersection with noice.nvim

### ISSUE THREAD

**Issue by kekscode** [soulis-1256/eagle.nvim#18]
Very cool plugin, i love it! Only i am doing something wrong in my config apparently and i was not able to fix it. Here is a screenshot:

<img width="751" alt="image" src="https://github.com/soulis-1256/eagle.nvim/assets/803252/8484c3aa-b03a-41d8-93d4-308ff215364d">

This shows:

- The hover window _above_ is what eagle shows me (screenshot does not include mouse pointer, but it is where the cursor is).
- The hover window _below_ is what `vim.lsp.buf.hover()` gives me with treesitter and noice installed (if that matters).

In your video in the `README.md` of this repo, i can see that eagle supports rendered output. So i think there must be something wrong with my setup, but i struggle to find out what it is.

Eagle's config snippet is this:

```lua
  {
    "soulis-1256/eagle.nvim", -- Following the mouse cursor hover, a custom floating window displays diagnostics (E/W/H) along with LSP info
    enabled = true,
    config = function()
      require("eagle").setup({
        render_delay = 250,
        title_color = "",  -- didn't like the default, so NO color here
        border_color = "", -- didn't like the default, so NO color here
        border = "rounded",
        window_row = 0,
        window_col = 5,
      })
    end
  },
```

I played with the config, the lsp server config, noice plugin config etc. but i was never able to get eagle's hover window to display the same colored/formatted output as `vim.lsp.buf.hover()` does.

**Comment by soulis-1256** [comment]
Hi, the plugin is indeed supposed to render markdown syntax and stylize it using some native functions, so your case is quite strange. You could try the following:

1. Change your config so that it strictly follows the README instructions. For whatever reason, overriding config options right where you load the plugin could cause the issue.
2. Try with another LSP provider and in another file/program altogether. One that I have tried is lua_ls (and it's light to install). If you choose the lua route, just open any lua file from your config and remove something to cause an error. Any other provider just to confirm the issue would be fine.

If none of the above work, come back specifying your Neovim version and I can start guiding you into debugging.

**Comment by soulis-1256** [comment]
Ok, so in my code I'm using `vim.lsp.util.convert_input_to_markdown_lines` and `vim.lsp.util.stylize_markdown` to render text inside the eagle window. If noice overrides these methods in whichever way, then my plugin is most likely not going to work properly. I will test noice myself right now using your config and try to find the option that introduces the issue. Hopefully I will come back with an answer.

**Comment by soulis-1256** [comment]
I had the same problem with you when using noice initially, and I fixed it by just doing:
```lua
["vim.lsp.util.stylize_markdown"] = false
```

inside lsp.override of noice's config. I don't know what this breaks for noice itself, but it's probably the most straightforward way to fix my plugin for now.

After this I kept going and instead of adding `= false`, I removed that line altogether and it still had no issue (as noice is not supposed to override the method by default). What's strange is that you said you tried removing all these lines:
```lua
  lsp = {
    -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
    override = {
      ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
      ["vim.lsp.util.stylize_markdown"] = false,
      ["cmp.entry.get_documentation"] = true, -- requires hrsh7th/nvim-cmp
    },
  },
```
which I also did and the issue would still not appear.

So since this fixed it for me, try adding `= false` and you should be good. If not, then we are looking at a deeper config issue.
